services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: appdb
    ports: ["5433:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
volumes: { pgdata: {} }
