name = "chorely-api"
main = "src/worker.ts"
compatibility_date = "2025-08-21"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[vars]
SUPABASE_URL = "https://nliyvlqddszmrsnybwrw.supabase.co"


