name: Deploy Worker (migrate -> publish)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      # --- Run Drizzle migrations against Neon ---
      - name: Run DB migrations (Drizzle -> Neon)
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: npm run db:migrate

      # --- Publish the Cloudflare Worker ---
      - name: Publish Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: backend
